baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-cookieyes'

[params.modules.cookieyes]
  local = true
  id = 'dummy'

[module]
  # Build and serve using local mod-cookieyes clone declared in the named Hugo workspace:
  workspace = "mod-cookieyes.work"
  [[module.imports]]
    path = "github.com/gethinode/mod-cookieyes/v2"
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"
